"""t2-sentiment-agent replica: the Bitget-hosted GetAgent Playbook twin of the Agent Hub agent.

The runner executes ``python -m src.main``. Every module here imports only what the Playbook sandbox
allows (``references/sandbox-runtime.md``): ``getagent`` and a short list of standard-library
modules. ``policy_v1.py`` is generated by ``scripts/build_playbook.py`` from the primary agent's
``POLICY_V1`` and must never be edited by hand; every other module is written against it.
"""
