"""GENERATED by scripts/build_playbook.py from sentiment_agent.policy.POLICY_V1. Do not edit.

Every number the replica obeys, rendered from the primary agent's pre-registered
policy, so the Agent Hub agent and this Playbook cannot drift apart. POLICY_HASH is
the SHA-256 of POLICY_CANONICAL_JSON (computed outside the sandbox, which has no
hashlib) and is the digest the primary's genesis record pre-registers. Rebuild with:

    python scripts/build_playbook.py --out playbook/

INSTRUMENT_LIMITS: validation/demo_venue/universe_probe.json, live rows, probed 2026-09-24T10:31:13Z.
"""

import json


# --- Identity --------------------------------------------------------------------------------------

PACKAGE_NAME = 't2-sentiment-agent-replica'
POLICY_VERSION = 'policy-v1'
POLICY_HASH = '55ff779b5d6f2c55082be1b4db6c9fde53865213cade58232f64f372ad73aeaf'

# --- Universe --------------------------------------------------------------------------------------

UNIVERSE = (
    ('BTCUSDT', 'crypto', 8.3),
    ('SP500USDT', 'us_index', 266.5),
    ('NDX100USDT', 'us_index', 63.2),
    ('MSTRUSDT', 'us_equity', 316.2),
    ('HOODUSDT', 'us_equity', 383.0),
    ('CRCLUSDT', 'us_equity', 308.7),
    ('SNDKUSDT', 'us_equity', 348.2),
    ('COINUSDT', 'us_equity', 165.0),
    ('TSLAUSDT', 'us_equity', 113.7),
    ('GOOGLUSDT', 'us_equity', 104.7),
    ('METAUSDT', 'us_equity', 67.2),
    ('NVDAUSDT', 'us_equity', 129.9),
    ('AMZNUSDT', 'us_equity', 92.0),
    ('AAPLUSDT', 'us_equity', 82.3),
)
US_SESSION_ASSET_CLASSES = ('us_equity', 'us_index')
EXCLUDED = ('ETHUSDT', 'SOLUSDT', 'XRPUSDT', 'DOGEUSDT')

# --- Kernel (G1-G11) -------------------------------------------------------------------------------

PER_NAME_MAX = 0.05
GROSS_MAX = 0.25
STOP_LOSS_PCT = 0.04
STOP_TRIGGER = 'mark'
DAILY_KILL_PCT = 0.015
MAX_REBALANCES_PER_NAME_PER_DAY = 2
MIN_HOLD_HOURS = 24
FEE_BUDGET_DAILY_BPS = 7.0
FEE_BUDGET_WINDOW_BPS = 20.0
TAKER_ONLY = True
MAX_OPEN_SPREAD_BPS = 20.0
MARK_INDEX_MAX_GAP = 0.03
STALE_INDEX_MIN_MOVE_BPS_3H = 2.0
GROUNDING_TOLERANCE = 0.02
GUARD_IDS = (
    'G1_venue_integrity',
    'G2_weekend_freeze',
    'G3_size',
    'G4_stop',
    'G5_daily_kill',
    'G6_turnover',
    'G7_fee_budget',
    'G8_taker_only',
    'G9_grounding',
    'G10_breaker',
    'G11_eligibility',
)

# --- Weekend freeze (G2) ---------------------------------------------------------------------------

WEEKEND_FREEZE_WEEKDAY = 4
WEEKEND_FREEZE_HOUR = 20
WEEKEND_REOPEN_WEEKDAY = 0
WEEKEND_REOPEN_HOUR = 0
WEEKEND_PREFLATTEN_MINUTES = 15
WEEKEND_NO_OPEN_BUFFER_HOURS = 2.0

# --- Circuit breaker (G10) -------------------------------------------------------------------------

BREAKER_REDUCE_ONLY_DRAWDOWN = 0.025
BREAKER_HALT_DRAWDOWN = 0.04
BREAKER_LOSING_STREAK_REDUCE_ONLY = 4
BREAKER_SNAPSHOT_MAX_AGE_MINUTES = 15
BREAKER_QUOTE_MAX_AGE_SECONDS = 120

# --- Triggers --------------------------------------------------------------------------------------

TRIGGER_US_OPEN_LOCAL = '09:30'
TRIGGER_FUNDING_HEARTBEAT_HOURS_UTC = (0, 8, 16)
TRIGGER_FEAR_GREED_LOW = 25
TRIGGER_FEAR_GREED_HIGH = 76
TRIGGER_FUNDING_Z_THRESHOLD = 2.0
TRIGGER_FUNDING_Z_LOOKBACK_SETTLEMENTS = 90
TRIGGER_OI_JUMP_QUANTILE = 0.99
TRIGGER_OI_JUMP_LOOKBACK_DAYS = 30
TRIGGER_COORDINATED_MIN_SOURCES = 3
TRIGGER_COORDINATED_WINDOW_MINUTES = 120
TRIGGER_EARNINGS_LOOKAHEAD_HOURS = 24
TRIGGER_COOLDOWN_MINUTES = 240
TRIGGER_MAX_EVENT_DECISIONS_PER_DAY = 8

# --- Decision and mandate --------------------------------------------------------------------------

DECISION_PRIMARY_MODEL = 'qwen3.8-max'
DECISION_MAX_ATTEMPTS = 3
DECISION_MAX_COMPLETION_TOKENS = 8192
DECISION_CALL_TIMEOUT_SECONDS = 600
DECISION_MIN_HORIZON_HOURS = 24
DECISION_TEMPERATURE = 0.0
DECISION_DAILY_TOKEN_CAP = 2400000
MANDATE_RISK_BUDGET_GROSS = 0.25
MANDATE_PER_NAME_MAX = 0.05
MANDATE_MIN_HORIZON_HOURS = 24
MANDATE_TEXT = (
    "You manage a paper book on Bitget's Demo venue. You hold a risk budget of up to "
    '25% of equity gross, at most 5% of equity in any one name, long or short. At eve'
    'ry decision you either deploy some of that budget, with a written thesis and inv'
    'alidation per position, or decline it in writing. Flat with reasons is a valid, '
    'counted answer. A risk kernel you do not control may shrink or refuse what you a'
    'sk for; it can never add to it.'
)

# --- Measured bases, one per guard -----------------------------------------------------------------

GUARD_RULES = {
    'G10_breaker': (
        'Drawdown from peak 2.5% -> reduce-only; 4% -> halted; 4 losing trades in a row -'
        '> reduce-only; a snapshot older than 15 min or a quote older than 120 s cannot o'
        'pen; a model outage flattens the book.'
    ),
    'G11_eligibility': (
        'Only the 14 universe symbols, only when Demo lists them online, only at or above'
        ' minOrderQty and minOrderAmount after rounding to quantityMultiplier; orders abo'
        've maxMarketOrderQty are split.'
    ),
    'G1_venue_integrity': (
        'Refuse or exit an instrument whose Demo mark departs more than 3% from its Demo '
        'index, whose Demo-live price gap exceeds its measured p99, or whose Demo index h'
        'as not moved (mean |1H move| over 3h below 2 bps) while its session should be op'
        'en.'
    ),
    'G2_weekend_freeze': (
        'US-equity and US-index legs flat from Friday 20:00 UTC to Monday 00:00 UTC; pre-'
        'flatten from 19:45; no new equity exposure in the 2h before the freeze.'
    ),
    'G3_size': 'At most 5% of equity per name and 25% gross.',
    'G4_stop': 'Every exposure-adding order carries a venue stop 4% from entry, triggered on mark.',
    'G5_daily_kill': (
        'Book down 1.5% from the 00:00 UTC equity flattens everything; halted until the n'
        'ext UTC day.'
    ),
    'G6_turnover': (
        'At most 2 model-initiated orders per name per UTC day; no increase or side flip '
        'within 24h of the last increase unless the model declares the stated invalidatio'
        'n fired. Reductions are never blocked (see DESIGN.md \xa710.4).'
    ),
    'G7_fee_budget': 'No new exposure once fees paid today reach 7 bps of equity, or 20 bps over the window.',
    'G8_taker_only': 'Market (taker) orders only; refuse an opening when the Demo spread exceeds 20 bps.',
    'G9_grounding': (
        'A target whose thesis, invalidation or view states a number that does not resolv'
        'e to a snapshot fact within 2% may not add exposure.'
    ),
}
GUARD_BASES = {
    'G10_breaker': (
        '2.5% is past the worst no-edge 72h drawdown (-2.48%, envelope_clean.json); losin'
        'g-streak and staleness rules ported from ARGUS risk/circuit.py (MIT); a model ou'
        'tage never leads to a deterministic trade (DESIGN.md \xa79.5)'
    ),
    'G11_eligibility': (
        'Demo instrument limits (e.g. NVDAUSDT maxMarketOrderQty 60, minOrderQty 0.01) in'
        ' universe_probe.json'
    ),
    'G1_venue_integrity': (
        'Demo flash prints (BTCUSDT Demo mark 65.6% from its index, 2026-06-29 00:00 UTC)'
        '; excursion counts and p99 gaps in demo_integrity.json and fade_demo.json; weeke'
        'nd Demo index moves 0.1-1.5 bps/h vs 18-66 bps/h on weekdays (weekend_vol.json)'
    ),
    'G2_weekend_freeze': (
        'UTA Demo does not track these perps on weekends. Mostly it freezes: weekend mean'
        ' |1H move| of the Demo index 0.1-1.5 bps against 5.6-29.1 bps live (weekend_vol.'
        'json); MSTR +204 bps live vs +5 bps Demo from Saturday 00:00 to 12:00 UTC on 202'
        '6-09-19. Sometimes it jumps on its own: AAPL +80 bps Demo vs +17 bps live on 202'
        '6-09-12 (fade_demo2.txt)'
    ),
    'G3_size': (
        'Envelope at 25% gross: worst 72h drawdown -2.48% under no edge (envelope_clean.j'
        'son); the drawdown is the one quantitative number design controls'
    ),
    'G4_stop': (
        'Envelope simulation uses -4% per position (envelope_clean.py); a stop that lives'
        ' on the venue survives a crashed agent, one that lives in our loop does not'
    ),
    'G5_daily_kill': 'Envelope simulation uses a -1.5% daily kill (envelope_clean.py)',
    'G6_turnover': (
        'Round-trip cost 12-16 bps against a measured intraday edge of ~0.00% on these pe'
        "rps; 360+ intraday variants were negative in the author's earlier study (not in "
        'this repository)'
    ),
    'G7_fee_budget': (
        'Demo taker fee 6 bps (instruments takerFeeRate 0.0006 on all 14 names, universe_'
        'probe.json); envelope expects ~11 round trips at 5% = 6.6 bps of equity per 72h;'
        ' caps are about 3x that'
    ),
    'G8_taker_only': (
        'Maker fills are adversely selected: a +90% limit-fill simulation replayed at -0.'
        "45% in the author's earlier fill-model replay (not in this repository). Demo spr"
        'eads measured 0.1-6.6 bps (universe_probe.json)'
    ),
    'G9_grounding': (
        'An unattributable figure is where an unsupported fact enters a trade. The check '
        'is ported from ARGUS agents/grounding.py (MIT); its fabricated-figure test set i'
        's re-run in this repository (tests/decision/test_grounding.py) rather than cited'
    ),
}

# --- Mirrored from the primary's modules (perception, grounding, crowd, decision, planner) ---------

MEASURED_TAKER_FEE = '0.0006'
FEATURE_MA_BARS = 20
FEATURE_ATR_BARS = 14
FEATURE_STALE_INDEX_MOVES = 3
FEATURE_FUNDING_SD_FLOOR = 1e-06
FEATURE_OI_MAX_AGE_MINUTES = 180.0
FEATURE_OI_MATCH_TOLERANCE_MINUTES = 5.0
FEATURE_FEAR_UPPER = 45
FEATURE_NEUTRAL_UPPER = 55
GROUNDING_MIN_MAGNITUDE = 1e-09
GROUNDING_CONTEXT_WINDOW = 32
GROUNDED_FIELDS = ('thesis', 'invalidation', 'our_view')
GROUNDING_PERCENT_TOKENS = ('pct', 'percent')
GROUNDING_BPS_TOKENS = ('bp', 'bps')
GROUNDING_FRACTION_TOKENS = (
    'change',
    'chg',
    'confidence',
    'drawdown',
    'fraction',
    'gap',
    'move',
    'premium',
    'rate',
    'return',
    'spread',
    'tolerance',
    'volatility',
    'weight',
    'yield',
)
NOVELTY_SHINGLE_WORDS = 4
NOVELTY_DUPLICATE_AT = 0.55
NOVELTY_MIN_COORDINATION_WORDS = 4
ALIASES = {
    'AAPLUSDT': {
        'cashtags': ('AAPL',),
        'names': (),
        'proper_names': ('Apple',),
        'tickers': ('AAPL',),
        'upper_tickers': (),
    },
    'AMZNUSDT': {
        'cashtags': ('AMZN',),
        'names': (),
        'proper_names': ('Amazon',),
        'tickers': ('AMZN',),
        'upper_tickers': (),
    },
    'BTCUSDT': {
        'cashtags': ('BTC', 'XBT'),
        'names': ('bitcoin',),
        'proper_names': (),
        'tickers': ('BTC', 'XBT'),
        'upper_tickers': (),
    },
    'COINUSDT': {
        'cashtags': ('COIN',),
        'names': ('coinbase',),
        'proper_names': (),
        'tickers': (),
        'upper_tickers': (),
    },
    'CRCLUSDT': {
        'cashtags': ('CRCL',),
        'names': ('circle internet',),
        'proper_names': (),
        'tickers': ('CRCL',),
        'upper_tickers': (),
    },
    'GOOGLUSDT': {
        'cashtags': ('GOOGL', 'GOOG'),
        'names': (),
        'proper_names': ('Alphabet', 'Google'),
        'tickers': ('GOOGL', 'GOOG'),
        'upper_tickers': (),
    },
    'HOODUSDT': {
        'cashtags': ('HOOD',),
        'names': ('robinhood',),
        'proper_names': (),
        'tickers': (),
        'upper_tickers': (),
    },
    'METAUSDT': {
        'cashtags': ('META',),
        'names': ('meta platforms',),
        'proper_names': ('Meta',),
        'tickers': (),
        'upper_tickers': (),
    },
    'MSTRUSDT': {
        'cashtags': ('MSTR',),
        'names': ('microstrategy',),
        'proper_names': (),
        'tickers': ('MSTR',),
        'upper_tickers': (),
    },
    'NDX100USDT': {
        'cashtags': ('NDX', 'QQQ'),
        'names': ('nasdaq 100', 'nasdaq-100', 'nasdaq100'),
        'proper_names': (),
        'tickers': ('NDX', 'NDX100', 'QQQ'),
        'upper_tickers': (),
    },
    'NVDAUSDT': {
        'cashtags': ('NVDA',),
        'names': ('nvidia',),
        'proper_names': (),
        'tickers': ('NVDA',),
        'upper_tickers': (),
    },
    'SNDKUSDT': {
        'cashtags': ('SNDK',),
        'names': ('sandisk',),
        'proper_names': (),
        'tickers': ('SNDK',),
        'upper_tickers': (),
    },
    'SP500USDT': {
        'cashtags': ('SPX', 'SPY'),
        'names': ('s&p 500', 's&p500', 's & p 500'),
        'proper_names': (),
        'tickers': ('SP500', 'SPX'),
        'upper_tickers': ('SPY',),
    },
    'TSLAUSDT': {
        'cashtags': ('TSLA',),
        'names': ('tesla',),
        'proper_names': (),
        'tickers': ('TSLA',),
        'upper_tickers': (),
    },
}
DECISION_INITIAL_COMPLETION_TOKENS = 4096
DECISION_TRUNCATION_GROWTH = 3

# --- This package ----------------------------------------------------------------------------------

CRON_MINUTES = 15
SCHEDULE_CRON = '*/15 * * * *'
SCHEDULE_TZ = 'UTC'
LEVERAGE = 1
INSTRUMENT_LIMITS = {
    'AAPLUSDT': ('0.01', '0.01', '5'),
    'AMZNUSDT': ('0.01', '0.01', '5'),
    'BTCUSDT': ('0.0001', '0.0001', '5'),
    'COINUSDT': ('0.01', '0.01', '5'),
    'CRCLUSDT': ('0.01', '0.01', '5'),
    'GOOGLUSDT': ('0.01', '0.01', '5'),
    'HOODUSDT': ('0.01', '0.01', '5'),
    'METAUSDT': ('0.01', '0.01', '5'),
    'MSTRUSDT': ('0.01', '0.01', '5'),
    'NDX100USDT': ('0.0001', '0.0001', '5'),
    'NVDAUSDT': ('0.01', '0.01', '5'),
    'SNDKUSDT': ('0.001', '0.001', '5'),
    'SP500USDT': ('0.0001', '0.0001', '5'),
    'TSLAUSDT': ('0.01', '0.01', '5'),
}
EVIDENCE_ROLE = 'secondary'
PRIMARY_LOG = (
    't2-sentiment-agent: Bitget UTA Demo orders through Agent Hub (bgc --paper-tradin'
    'g), hash-chained ledger published as public/ledger.jsonl, pre-registered at gene'
    'sis'
)

# --- The whole policy -------------------------------------------------------------------------------

POLICY_CANONICAL_JSON = (
    '{"breaker":{"basis":"See GuardBasis G10","halt_drawdown":0.04,"losing_streak_red'
    'uce_only":4,"quote_max_age_seconds":120,"reduce_only_drawdown":0.025,"snapshot_m'
    'ax_age_minutes":15},"daily_kill_pct":0.015,"decision":{"basis":"FULL reasoning o'
    'n the <=4 daily heartbeats, LOW on <=8 event decisions: measured FULL ~4.3k and '
    'LOW ~0.8k completion tokens per call (ARGUS llm/qwen.py). Streaming is required '
    'for FULL: the gateway closes unstreamed requests at ~120 s. The cap is sized to '
    "the budget's own projection (llm/budget.py: one token per prompt byte plus the c"
    'ompletion cap), prompt included, for the busiest day the trigger rules allow: re'
    'corded dry-run prompt 40,784 B (system 11,898 + user 28,886), x1.25 headroom = 5'
    '0,980 B; one attempt = 50,980 + 2x16 + 128 + 8,192 = 59,332; a retry adds 8,192 '
    '+ 32 = 67,556; three attempts = 194,444 per decision; (4 heartbeats + 8 events) '
    'x 194,444 = 2,333,328, rounded up to 2,400,000. Real spend is lower (a byte boun'
    'ds a token from above); the prompt_tokens of the first live calls re-check it be'
    'fore genesis. Owner requests are outside this sum; the heartbeats left in the da'
    "y are reserved before an event decision is admitted. The cap is the owner's to a"
    'pprove.","call_timeout_seconds":600,"daily_token_cap":2400000,"max_attempts":3,"'
    'max_completion_tokens":8192,"min_horizon_hours":24,"model":"qwen3.8-max","temper'
    'ature":0.0,"thinking_event":"low","thinking_heartbeat":"full"},"excluded":["ETHU'
    'SDT","SOLUSDT","XRPUSDT","DOGEUSDT"],"expected_envelope":{"closed_trades":"media'
    'n 11","max_drawdown_pct":"median -0.42, p95 -1.10, worst -2.48","return_on_equit'
    'y_bps":"median -8.6, p05 -88.1, p95 +80.6","sharpe_ann":"median -2.3, p05 -20.2,'
    ' p95 +16.8","source":"validation/demo_venue/envelope_clean.json (no-edge coin-fl'
    'ip book, 17,400 windows of 72h, 25% gross)","win_rate":"median 0.45, p05 0.18, p'
    '95 0.71"},"fee_budget_daily_bps":7.0,"fee_budget_window_bps":20.0,"gross_max":0.'
    '25,"grounding_tolerance":0.02,"guard_bases":[{"basis":"Demo flash prints (BTCUSD'
    'T Demo mark 65.6% from its index, 2026-06-29 00:00 UTC); excursion counts and p9'
    '9 gaps in demo_integrity.json and fade_demo.json; weekend Demo index moves 0.1-1'
    '.5 bps/h vs 18-66 bps/h on weekdays (weekend_vol.json)","guard":"G1_venue_integr'
    'ity","rule":"Refuse or exit an instrument whose Demo mark departs more than 3% f'
    'rom its Demo index, whose Demo-live price gap exceeds its measured p99, or whose'
    ' Demo index has not moved (mean |1H move| over 3h below 2 bps) while its session'
    ' should be open."},{"basis":"UTA Demo does not track these perps on weekends. Mo'
    'stly it freezes: weekend mean |1H move| of the Demo index 0.1-1.5 bps against 5.'
    '6-29.1 bps live (weekend_vol.json); MSTR +204 bps live vs +5 bps Demo from Satur'
    'day 00:00 to 12:00 UTC on 2026-09-19. Sometimes it jumps on its own: AAPL +80 bp'
    's Demo vs +17 bps live on 2026-09-12 (fade_demo2.txt)","guard":"G2_weekend_freez'
    'e","rule":"US-equity and US-index legs flat from Friday 20:00 UTC to Monday 00:0'
    '0 UTC; pre-flatten from 19:45; no new equity exposure in the 2h before the freez'
    'e."},{"basis":"Envelope at 25% gross: worst 72h drawdown -2.48% under no edge (e'
    'nvelope_clean.json); the drawdown is the one quantitative number design controls'
    '","guard":"G3_size","rule":"At most 5% of equity per name and 25% gross."},{"bas'
    'is":"Envelope simulation uses -4% per position (envelope_clean.py); a stop that '
    'lives on the venue survives a crashed agent, one that lives in our loop does not'
    '","guard":"G4_stop","rule":"Every exposure-adding order carries a venue stop 4% '
    'from entry, triggered on mark."},{"basis":"Envelope simulation uses a -1.5% dail'
    'y kill (envelope_clean.py)","guard":"G5_daily_kill","rule":"Book down 1.5% from '
    'the 00:00 UTC equity flattens everything; halted until the next UTC day."},{"bas'
    'is":"Round-trip cost 12-16 bps against a measured intraday edge of ~0.00% on the'
    "se perps; 360+ intraday variants were negative in the author's earlier study (no"
    't in this repository)","guard":"G6_turnover","rule":"At most 2 model-initiated o'
    'rders per name per UTC day; no increase or side flip within 24h of the last incr'
    'ease unless the model declares the stated invalidation fired. Reductions are nev'
    'er blocked (see DESIGN.md \xa710.4)."},{"basis":"Demo taker fee 6 bps (instruments '
    'takerFeeRate 0.0006 on all 14 names, universe_probe.json); envelope expects ~11 '
    'round trips at 5% = 6.6 bps of equity per 72h; caps are about 3x that","guard":"'
    'G7_fee_budget","rule":"No new exposure once fees paid today reach 7 bps of equit'
    'y, or 20 bps over the window."},{"basis":"Maker fills are adversely selected: a '
    "+90% limit-fill simulation replayed at -0.45% in the author's earlier fill-model"
    ' replay (not in this repository). Demo spreads measured 0.1-6.6 bps (universe_pr'
    'obe.json)","guard":"G8_taker_only","rule":"Market (taker) orders only; refuse an'
    ' opening when the Demo spread exceeds 20 bps."},{"basis":"An unattributable figu'
    're is where an unsupported fact enters a trade. The check is ported from ARGUS a'
    'gents/grounding.py (MIT); its fabricated-figure test set is re-run in this repos'
    'itory (tests/decision/test_grounding.py) rather than cited","guard":"G9_groundin'
    'g","rule":"A target whose thesis, invalidation or view states a number that does'
    ' not resolve to a snapshot fact within 2% may not add exposure."},{"basis":"2.5%'
    ' is past the worst no-edge 72h drawdown (-2.48%, envelope_clean.json); losing-st'
    'reak and staleness rules ported from ARGUS risk/circuit.py (MIT); a model outage'
    ' never leads to a deterministic trade (DESIGN.md \xa79.5)","guard":"G10_breaker","r'
    'ule":"Drawdown from peak 2.5% -> reduce-only; 4% -> halted; 4 losing trades in a'
    ' row -> reduce-only; a snapshot older than 15 min or a quote older than 120 s ca'
    'nnot open; a model outage flattens the book."},{"basis":"Demo instrument limits '
    '(e.g. NVDAUSDT maxMarketOrderQty 60, minOrderQty 0.01) in universe_probe.json","'
    'guard":"G11_eligibility","rule":"Only the 14 universe symbols, only when Demo li'
    'sts them online, only at or above minOrderQty and minOrderAmount after rounding '
    'to quantityMultiplier; orders above maxMarketOrderQty are split."}],"mandate":{"'
    'min_horizon_hours":24,"per_name_max":0.05,"risk_budget_gross":0.25,"text":"You m'
    "anage a paper book on Bitget's Demo venue. You hold a risk budget of up to 25% o"
    'f equity gross, at most 5% of equity in any one name, long or short. At every de'
    'cision you either deploy some of that budget, with a written thesis and invalida'
    'tion per position, or decline it in writing. Flat with reasons is a valid, count'
    'ed answer. A risk kernel you do not control may shrink or refuse what you ask fo'
    'r; it can never add to it."},"mark_index_max_gap":0.03,"max_open_spread_bps":20.'
    '0,"max_rebalances_per_name_per_day":2,"metrics":[{"formula":"r_t = E_t / E_{t-1}'
    ' - 1 on the UTC hour grid, E = equity_book","name":"hourly_return","notes":"Same'
    ' grid and definition as validation/demo_venue/envelope_clean.py","unit":"fractio'
    'n"},{"formula":"mean(r) / pstdev(r) * sqrt(8760)","name":"sharpe_ann","notes":"P'
    'opulation stdev, as envelope_clean.py. Undefined (None) when pstdev is 0.","unit'
    '":"annualised ratio"},{"formula":"sqrt((1 + 0.5 * S_h^2) / n) * sqrt(8760), S_h '
    '= mean(r) / pstdev(r)","name":"sharpe_se_ann","notes":"Lo (2002) iid standard er'
    'ror; about 11 at n = 72 with S_h near 0","unit":"annualised ratio"},{"formula":"'
    'mean(r) / sqrt(mean(min(r, 0)^2)) * sqrt(8760)","name":"sortino_ann","notes":"",'
    '"unit":"annualised ratio"},{"formula":"min_t (E_t / max_{s<=t} E_s - 1)","name":'
    '"max_drawdown","notes":"","unit":"fraction (non-positive)"},{"formula":"count(ne'
    't_pnl > 0) / count(closed trades)","name":"win_rate","notes":"A closed trade is '
    'one symbol from flat to flat; a flip closes one and opens one. net_pnl includes '
    'both fees. None when no trade has closed.","unit":"fraction"},{"formula":"sum(|f'
    'ill notional|) / mean(E)","name":"turnover","notes":"","unit":"multiple of equit'
    'y"},{"formula":"moving-block bootstrap of r, block = ceil(n^(1/3)) hours, 10,000'
    ' resamples, seed 20260924; 5th and 95th percentiles over the resamples where the'
    ' statistic is defined, the share where it is not published beside the band; the '
    'Sharpe ratio of an all-zero resample is 0","name":"ci90","notes":"Descriptive, n'
    'ot inferential: 72 hourly marks cannot separate skill from luck.","unit":"per me'
    'tric"}],"min_hold_hours":24,"per_name_max":0.05,"stale_index_min_move_bps_3h":2.'
    '0,"stop_loss_pct":0.04,"stop_trigger":"mark","taker_only":true,"triggers":{"basi'
    's":"Heartbeat and event list: DESIGN.md \xa78. Fear & Greed bands are Bitget\'s own '
    '(bitget-signal skills/sentiment-analyst/SKILL.md: 0-25 extreme fear, 76-100 extr'
    'eme greed). Coordination constants from ARGUS agents/novelty.py (3 sources insid'
    'e 2h). Live BTCUSDT funding settles every 8h (instruments fundInterval, re-read '
    'at genesis).","cooldown_minutes":240,"coordinated_min_sources":3,"coordinated_wi'
    'ndow_minutes":120,"earnings_lookahead_hours":24,"fear_greed_high":76,"fear_greed'
    '_low":25,"funding_heartbeat_hours_utc":[0,8,16],"funding_z_lookback_settlements"'
    ':90,"funding_z_threshold":2.0,"max_event_decisions_per_day":8,"oi_jump_lookback_'
    'days":30,"oi_jump_quantile":0.99,"us_open_local":"09:30"},"universe":[{"asset_cl'
    'ass":"crypto","basis":"p99 of |Demo close / live close - 1| over the Demo histor'
    'y, 1H candles (validation/demo_venue/demo_integrity.json); 0 mark-vs-index excur'
    'sions over 3% in the last 30 days","demo_live_gap_p99_bps":8.3,"symbol":"BTCUSDT'
    '"},{"asset_class":"us_index","basis":"p99 of |Demo close / live close - 1| over '
    'the Demo history, 1H candles (validation/demo_venue/demo_integrity.json); listed'
    ' on Demo 2026-09-03","demo_live_gap_p99_bps":266.5,"symbol":"SP500USDT"},{"asset'
    '_class":"us_index","basis":"p99 of |Demo close / live close - 1| over the Demo h'
    'istory, 1H candles (validation/demo_venue/demo_integrity.json); listed on Demo 2'
    '026-09-03","demo_live_gap_p99_bps":63.2,"symbol":"NDX100USDT"},{"asset_class":"u'
    's_equity","basis":"p99 of |Demo close / live close - 1| over the Demo history, 1'
    'H candles (validation/demo_venue/fade_demo.json (tracking)); 0 mark-vs-index exc'
    'ursions over 3% since Demo listing 2026-08-25","demo_live_gap_p99_bps":316.2,"sy'
    'mbol":"MSTRUSDT"},{"asset_class":"us_equity","basis":"p99 of |Demo close / live '
    'close - 1| over the Demo history, 1H candles (validation/demo_venue/fade_demo.js'
    'on (tracking)); 0 mark-vs-index excursions over 3% since Demo listing 2026-08-25'
    '","demo_live_gap_p99_bps":383.0,"symbol":"HOODUSDT"},{"asset_class":"us_equity",'
    '"basis":"p99 of |Demo close / live close - 1| over the Demo history, 1H candles '
    '(validation/demo_venue/fade_demo.json (tracking)); 0 mark-vs-index excursions ov'
    'er 3% since Demo listing 2026-08-25","demo_live_gap_p99_bps":308.7,"symbol":"CRC'
    'LUSDT"},{"asset_class":"us_equity","basis":"p99 of |Demo close / live close - 1|'
    ' over the Demo history, 1H candles (validation/demo_venue/fade_demo.json (tracki'
    'ng)); 0 mark-vs-index excursions over 3% since Demo listing 2026-08-25","demo_li'
    've_gap_p99_bps":348.2,"symbol":"SNDKUSDT"},{"asset_class":"us_equity","basis":"p'
    '99 of |Demo close / live close - 1| over the Demo history, 1H candles (validatio'
    'n/demo_venue/fade_demo.json (tracking)); 0 mark-vs-index excursions over 3% sinc'
    'e Demo listing 2026-08-25","demo_live_gap_p99_bps":165.0,"symbol":"COINUSDT"},{"'
    'asset_class":"us_equity","basis":"p99 of |Demo close / live close - 1| over the '
    'Demo history, 1H candles (validation/demo_venue/fade_demo.json (tracking)); 0 ma'
    'rk-vs-index excursions over 3% since Demo listing 2026-08-25","demo_live_gap_p99'
    '_bps":113.7,"symbol":"TSLAUSDT"},{"asset_class":"us_equity","basis":"p99 of |Dem'
    'o close / live close - 1| over the Demo history, 1H candles (validation/demo_ven'
    'ue/fade_demo.json (tracking)); 0 mark-vs-index excursions over 3% since Demo lis'
    'ting 2026-08-25","demo_live_gap_p99_bps":104.7,"symbol":"GOOGLUSDT"},{"asset_cla'
    'ss":"us_equity","basis":"p99 of |Demo close / live close - 1| over the Demo hist'
    'ory, 1H candles (validation/demo_venue/fade_demo.json (tracking)); 0 mark-vs-ind'
    'ex excursions over 3% since Demo listing 2026-08-25","demo_live_gap_p99_bps":67.'
    '2,"symbol":"METAUSDT"},{"asset_class":"us_equity","basis":"p99 of |Demo close / '
    'live close - 1| over the Demo history, 1H candles (validation/demo_venue/fade_de'
    'mo.json (tracking)); 0 mark-vs-index excursions over 3% since Demo listing 2026-'
    '08-25","demo_live_gap_p99_bps":129.9,"symbol":"NVDAUSDT"},{"asset_class":"us_equ'
    'ity","basis":"p99 of |Demo close / live close - 1| over the Demo history, 1H can'
    'dles (validation/demo_venue/fade_demo.json (tracking)); 0 mark-vs-index excursio'
    'ns over 3% since Demo listing 2026-08-25","demo_live_gap_p99_bps":92.0,"symbol":'
    '"AMZNUSDT"},{"asset_class":"us_equity","basis":"p99 of |Demo close / live close '
    '- 1| over the Demo history, 1H candles (validation/demo_venue/fade_demo.json (tr'
    'acking)); 0 mark-vs-index excursions over 3% since Demo listing 2026-08-25","dem'
    'o_live_gap_p99_bps":82.3,"symbol":"AAPLUSDT"}],"version":"policy-v1","weekend":{'
    '"basis":"Same window as the envelope simulation\'s tradable() (envelope_clean.py)'
    '; the Demo freeze itself is in weekend_vol.json","freeze_hour":20,"freeze_weekda'
    'y":4,"no_open_buffer_hours":2.0,"preflatten_minutes":15,"reopen_hour":0,"reopen_'
    'weekday":0}}'
)

POLICY = json.loads(POLICY_CANONICAL_JSON)
